# === Network Guard Permissions ===
net=dummy_network
net=eno1

# === USB Guard Permissions ===
usb=001372998035EA81E57900B3
usb=03028016011025064106

# === Bluetooth Guard Permissions ===
bt=C8:BC:9C:9A:E5:39
