# === Network Guard Permissions ===
net=eno1
net=dummy_network

# === USB Guard Permissions ===
usb=03028016011025064106
usb=001372998035EA81E57900B3

# === Bluetooth Guard Permissions ===
bt=C7:QC:SC:3E:F5:22