# === Network Guard Permissions ===
net=eno1
net=dummy_network

# === USB Guard Permissions ===
# SanDisk Flash Drive
usb=001372998035EA81E57900B3

# === Bluetooth Guard Permissions ===
bt=AA:BB:CC:DD:EE:FF